
title: Currículo
url: ''
baseurl: '/curriculo'

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Antonino Calisto
tagline: Mestre em Engenharia Elétrica com ênfase em Ciências da Computação
pic: profile.jpg
location: São luís, MA, BR

#sidebar links
email: antuninosantos@gmail.com
website: antonino.github.io
linkedin: antoninocalisto
github: antoninocalisto

#Update all the sections by editing the files inside _includes folder.
