
title: Currículo
url: ''
baseurl: '/curriculo'

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: João Lucas
tagline: Engenheiro de Software
pic: profile.jpg
location: Juiz de Fora, MG

#sidebar links
email: joaolucasgtr@gmail.com
website: joaolucasgtr.github.io
linkedin: joaolucasgtr
github: joaolucasgtr

#Update all the sections by editing the files inside _includes folder.
